sudo: required
language: python
python:
- 3.6
services:
- docker
cache:
  pip: true
  directories:
  - _build
  - deps
  - $HOME/docker
env:
  global:
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY is in travis-ci.com
  - SERVICE_NAME=danbi
  - TASK_DEFINITION=danbi
  - IMAGE_NAME=danbi
  - REMOTE_IMAGE_URL=800074035736.dkr.ecr.ap-northeast-1.amazonaws.com/danbi
install:
- pip install flake8 codecov awscli
- pip install -r requirements.txt
script:
- flake8 .
- pytest --cov=./
- if [[ -e $HOME/docker/image.tar ]]; then;
  docker load -i $HOME/docker/image.tar;
  fi
- docker build -t $IMAGE_NAME .
- docker save ${IMAGE_NAME}:latest > ${HOME}/docker/image.tar
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  eval $(aws ecr get-login --region ap-northeast-1);
  docker tag $IMAGE_NAME:latest "$REMOTE_IMAGE_URL:latest";
  docker push "$REMOTE_IMAGE_URL:latest";
  etc/ecs-deploy.sh -c ${TASK_DEFINITION} -n ${SERVICE_NAME} -i ${REMOTE_IMAGE_URL}:latest;
  fi
