sudo: required
language: python
python:
- 3.6
services:
- docker
- postgresql
addons:
  postgresql: "9.6"
cache:
  pip: true
  directories:
  - _build
  - deps
  - $HOME/docker
env:
  global:
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY is in travis-ci.com
  - REGION=ap-northeast-1
  - SERVICE_NAME=danbi
  - TASK_DEFINITION=danbi
  - IMAGE_NAME=danbi
  - REMOTE_IMAGE_URL=800074035736.dkr.ecr.ap-northeast-1.amazonaws.com/danbi
  - DEPLOYMENT_LEVEL=staging
install:
- pip install flake8 codecov awscli 'pyflakes>1.4.0'
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- flake8 .
- pytest --cov=./
- docker build -t $IMAGE_NAME .
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  eval $(aws ecr get-login --region $REGION);
  docker tag $IMAGE_NAME:latest "$REMOTE_IMAGE_URL:latest";
  docker push "$REMOTE_IMAGE_URL:latest";
  etc/ecs-deploy.sh -r $REGION -c $TASK_DEFINITION -n $SERVICE_NAME -i $REMOTE_IMAGE_URL:latest;
  fi
