language: python
sudo: false
python:
- 3.6
install:
- pip install flake8 codecov
- pip install -r requirements.txt
script:
- flake8 .
- pytest --cov=./
after_success:
- bash <(curl -s https://codecov.io/bash)
